Página "Sobre"
Guardians-DSC/Front-HoCo pull request #21
Opened 2021-09-18 02:08 UTC by RuanGOA

Antes de fazer o PR por favor preencha o seguinte formulário:

### Meu pull request

- [X] Adiciona uma nova funcionalidade;
- [X] Conserta um bug;
- [ ] Adiciona uma documentação;
- [ ] Adiciona alguma configuração.

### O que o pull request faz?

Foi criada a página "Sobre" do projeto.
  - Dentro da pasta `services`, foi criado um serviço para busca de contribuidores dos projetos relacionados ao HoCo.
  - Foi criado um componente de contribuidores, seguindo a especificação feita no Figma.

Foi corrigido um bug de surgimento indevido de scroll horizontal na página, ocasionado pelo surgimento do scroll vertical.

Foi adicionado um conjunto de estilos (`src/views/commom.js`) que todas as páginas poderão utilizar para padronizar, como título, subtítulo, link (âncora) e parágrafo. Isso foi feito para que não haja duplicação de código. Imagino que com desenvolvimento do restante do projeto, outros elementos poderão ser adicionados, se necessário.

### Como faço para testar essa PR?

Acessando a aplicação na rota `/sobre`, pois o consumo de dados é feito da API do Github.

### Mais infos

O _pull request_ vai ficar um pouco maior do que deveria porque estou resolvendo as issues #13 e #6. Como as duas estavam muito imaginei que pudessem estar no mesmo PR.

### Para finalizar tenha certeza que a PR

- [ ] Está bem documentado;
- [ ] Adiciona testes se necessário;
- [ ] Passa nos testes existentes (caso existam).

### Para finalizar...

Por favor marque os revisadores @rodrigoec, @leandraoliveira, @claudiodantas e @gustavofss. Após duas aprovações a sua PR será merjada na branch `develop` até que uma release seja feita.

Bom, obrigado por sua contribuição!💙 Projetos open source só vão pra frente por causa de gente com você que está disposto(a)(e) a contribuir e manter o projeto vivo.

<div align=center>
  <img width=350px src='https://user-images.githubusercontent.com/42751604/130703676-2e16abb1-3392-4f76-a9ec-a4973f638e2d.gif'/>
</div>

2021-09-18 12:54 UTC, RodrigoEC requested changes
Arrasou @RuanGOA!! Ficou muito legal, eu só apontei algumas coisas de proporções, princiaplmente no arquivo `common.js` mas ta muito massa.

2021-09-18 12:54 UTC, RodrigoEC commented on src/components/Contributors/style.js
> +  gap: 1.5vw;
Utiliza o `rem` por favor amigo, já que é a medida que a gente ta usando no projeto mesmo pra essas coisas

2021-09-18 12:54 UTC, RodrigoEC commented on src/components/Contributors/style.js
> +    width: 10vh;
Utilizar `rem` como dito antes. Além disso é interessante tentar preservar as dimensões definidas no figma, acho que `4rem` para o tamanho da imagem já pode ficar interessante

2021-09-18 12:54 UTC, RodrigoEC commented on src/services/github.js
> +    let contributors = await Promise.all(
Esse `Promise.all / .then` é realmente necessário? Pelo que eu entendo o await é serve justamente para a gente dizer pro javaScript esperar a promise ser resolvida

2021-09-18 12:54 UTC, RodrigoEC commented on src/views/common.js
> +	margin: 2rem 5rem;
Acho que a margem dos lados ta muito grande, mudar para 

```suggestion
	margin: 3.5rem 2.5rem;
```

2021-09-18 12:54 UTC, RodrigoEC commented on src/views/common.js
> +		font-size: 1.25rem;
A `font-size` do parágrafo pode ser 1rem mesmo

```suggestion
		font-size: 1rem;
```

2021-09-18 12:54 UTC, RodrigoEC commented on src/views/common.js
> +			font - weight: bold;
```suggestion
			font-weight: bold;
```

2021-09-18 12:54 UTC, RodrigoEC commented on src/views/common.js
> +			text - decoration: underline;
```suggestion
			text-decoration: underline;
```

2021-09-18 12:54 UTC, RodrigoEC commented on src/views/common.js
> +	display: flex;
Acho que o problema de utilizar flex e um gap aqui é que os espaçamentos entre os conteúdos, título e parágrafo por exemplo não são respeitados. Por exemplo na página de sobre o título teoricamente teria 1rem de margin-bottom, mas ele acaba tendo mais por causa do gap.

2021-09-18 12:54 UTC, RodrigoEC commented on src/views/common.js
> +  font-size: 1.75rem;
```suggestion
  font-size: 1.25rem;
```

2021-09-18 12:54 UTC, RodrigoEC commented on src/views/common.js
> +	& > p {
Definir um componente próprio da tag `p` chamado `Text`

2021-09-18 12:54 UTC, RodrigoEC commented on src/views/common.js
> +  margin-bottom: 1rem;
```suggestion
  margin-bottom: 2rem;
```

2021-09-18 12:54 UTC, RodrigoEC commented on src/views/common.js
> +  margin-bottom: 1rem;
```suggestion

```

2021-09-18 12:54 UTC, RodrigoEC commented on src/views/common.js
> +  margin: 1rem 0;
```suggestion
  margin: 1.5rem 0;
```

2021-09-18 12:59 UTC, RodrigoEC commented
Ah, algo que eu esqueci de falar, acho que seria legal mudar o nome do arquivo de `common.js` para `base-styles.js` e colocar ele na pasta styles onde fica o reset.css

2021-09-18 13:57 UTC, RodrigoEC commented
Meu deus o flood, mas amigo tava pensando aqui e mexendo, acho que seria muito legal se os spans do Text pudessem ficar nesse estilo:

![image](https://user-images.githubusercontent.com/42751604/133891252-8b02b6f2-dc3f-4921-90e3-77eab0e4c3a7.png)

É algo que não tem no design mas acho que ficaria bem legal, isso evita de ficar um negrito muito grande mas ainda fica marcado

2021-09-18 16:36 UTC, RuanGOA commented on src/services/github.js
> +    let contributors = await Promise.all(
Nessa função, são utilizados os nomes dos repositórios relacionados ao HoCo para buscar os contribuidores de cada um desses. Acredito que por isso eu precise do `Promise.all`, mas vou procurar se a API do Github possui alguma forma de trazer informações de mais de um repositório por vez, assim faço apenas uma requisição e a aguardo.

2021-09-18 16:38 UTC, RuanGOA commented on src/services/github.js
> +    let contributors = await Promise.all(
Bem observado hahahaha. Valeu.

2021-09-18 16:43 UTC, RuanGOA commented on src/views/common.js
> +			font - weight: bold;
Acho que commitei isso quando fui corrigir erros de linter xD

2021-09-18 16:47 UTC, RuanGOA commented on src/views/common.js
> +	display: flex;
Você sugere que eu remova o gap? Eu percebi agora que não observeis os valores do Figma, mas eu tive a impressão que os títulos tinham um `margin-bottom` maior mesmo. Não achar que seria mais interessante remover o margin bottom?

2021-09-18 16:48 UTC, RuanGOA commented on src/views/common.js
> +	display: flex;
Acredito que utilizar o gap seja interessante para padronizar os espaçamentos e evitar ter que colocar margin em todos os elementos da página.

2021-09-18 16:56 UTC, RuanGOA commented
> Ah, algo que eu esqueci de falar, acho que seria legal mudar o nome do arquivo de `common.js` para `base-styles.js` e colocar ele na pasta styles onde fica o reset.css

Boa! Eu também tinha achado o nome "common" estranho nesse contexto, acabei dando o nome para não ficar parado e esqueci de pensar em um melhor no final.

2021-09-18 17:05 UTC, RuanGOA commented
> Meu deus o flood, mas amigo tava pensando aqui e mexendo, acho que seria muito legal se os spans do Text pudessem ficar nesse estilo:
> 
> ![image](https://user-images.githubusercontent.com/42751604/133891252-8b02b6f2-dc3f-4921-90e3-77eab0e4c3a7.png)
> 
> É algo que não tem no design mas acho que ficaria bem legal, isso evita de ficar um negrito muito grande mas ainda fica marcado

Concordo completamente contigo. Gostei bastante dessa forma.

2021-09-18 17:14 UTC, RuanGOA commented on src/views/Sobre/index.js
> +          {`Olá! o Hoco é uma plataforma idealizada por alunos da graduação com
Passei os textos que estavam indo direto no JSX para utilização de strings do próprio Javascript, para evitar que tenha algum problema no espaçamento das palavras, ou quebras de linha.

2021-09-18 22:08 UTC, RodrigoEC requested changes
Muito bom, apontei mais algumas coisinhas, lembra de mover o arquivo `base-styles.js` pra a pasta **`styles`**

2021-09-18 22:08 UTC, RodrigoEC commented on src/views/base-styles.js
> +  width: 100%;
Remover margin do componente Content e adicionar padding aqui com o mesmo valor do margin

```
    padding: 3.5rem 2.5rem
```

Acho que seria mais interessante ao inves de colocar esse componente em cada página, coloca-lo no arquivo `App.js` no lugar da tag `body`

2021-09-18 22:08 UTC, RodrigoEC commented on src/views/base-styles.js
> +  margin: 3.5rem 2.5rem;
```suggestion

```

2021-09-18 22:08 UTC, RodrigoEC commented on src/views/base-styles.js
> +  gap: 2rem;
```suggestion

```

2021-09-18 22:08 UTC, RodrigoEC commented on src/views/base-styles.js
> +  font-size: 3rem;
```suggestion
  font-size: 2rem;
```

2021-09-18 22:08 UTC, RodrigoEC commented on src/views/base-styles.js
> +    background: #dfdfdf;
```suggestion
    background: #dfdfdf;
    padding: 0rem 0.25rem;
    border-radius: 5px;
```

2021-09-18 22:08 UTC, RodrigoEC commented on src/views/base-styles.js
> +
```suggestion
  margin-bottom: 0.5rem;
  line-height: 1.5rem;
```

2021-09-18 22:08 UTC, RodrigoEC commented on src/views/base-styles.js
> +  font-size: 1rem;
```suggestion
  font-size: 1.2rem;
```

2021-09-18 22:16 UTC, RodrigoEC commented on src/views/base-styles.js
> +  font-weight: 600;
```suggestion
  font-weight: 500;
```

2021-09-18 22:17 UTC, RodrigoEC commented on src/views/Sobre/index.js
> +        </Title>
```suggestion
        </Title>
        <Subtitle>O que é o HoCo?</Subtitle>
```

2021-09-18 22:18 UTC, RodrigoEC commented on src/components/Contributors/style.js
> +  gap: 1.5rem;
```suggestion
  gap: 1rem;
```

2021-09-19 03:49 UTC, RodrigoEC approved these changes

2021-09-19 05:10 UTC, merged