Adiciona componente de gráfico de pizza
Guardians-DSC/Front-HoCo pull request #23
Opened 2021-09-19 05:40 UTC by RodrigoEC

Antes de fazer o PR por favor preencha o seguinte formulário:

### Meu pull request

- [X] Adiciona uma nova funcionalidade;
- [ ] Conserta um bug;
- [ ] Adiciona uma documentação;
- [ ] Adiciona alguma configuração.

### O que o pull request faz?

Adiciona componente de um gráfico de pizza, `PieChart`.

### Como faço para testar essa PR?

Basta apenas executar o projeto e entra na pagina de horas.

### Mais infos

### Para finalizar tenha certeza que a PR

- [ ] Está bem documentado;
- [ ] Adiciona testes se necessário;
- [ ] Passa nos testes existentes (caso existam).

### Para finalizar...

Por favor marque os revisadores @rodrigoec, @leandraoliveira, @claudiodantas e @gustavofss. Após duas aprovações a sua PR será merjada na branch `develop` até que uma release seja feita.

Bom, obrigado por sua contribuição!💙 Projetos open source só vão pra frente por causa de gente com você que está disposto(a)(e) a contribuir e manter o projeto vivo.

<div align=center>
  <img width=350px src='https://user-images.githubusercontent.com/42751604/130703676-2e16abb1-3392-4f76-a9ec-a4973f638e2d.gif'/>
</div>

2021-09-19 05:41 UTC, RodrigoEC commented
@pedroespindula da uma revisada também, por favor.

2021-09-19 15:30 UTC, LeandraOS approved these changes
Achei a implementação ótima! Além da lindeza que está, tanto para web quanto pra o mobile. 
Incrível! :rocket:

2021-09-22 22:13 UTC, pedroespindula requested changes
Oi, @RodrigoEC, imagino o trabalho gigantesco pra fazer esse gráfico de pizza. Parabéns, ficou muito bom!  Mesmo assim, fiz alguns comentários que acredito serem relevantes. Além disso, me incomodou um pouco o alinhamento do texto com as seções do gráfico (Não sei o que pode ser feito para isso melhorar).

2021-09-22 22:13 UTC, pedroespindula commented on src/util/util.js
> +}
Tu poderia simplificar esse código da seguinte forma:
```suggestion
export function compare(a, b) {
  return b.value - a.value
}
```

2021-09-22 23:27 UTC, RodrigoEC commented on src/components/CreditsPieChart/index.js
> +  }
arrasou, vou fazer isso

2021-09-22 23:28 UTC, RodrigoEC commented on src/components/CreditsPieChart/index.js
> +        Você tem 11 créditos aprovados atualmente e as suas principais fontes de
Sim sim, vou colocar um TODO nisso, a ideia é que tenha mesmo

2021-09-23 01:11 UTC, merged