Página "Organizações"
Guardians-DSC/Front-HoCo pull request #29
Opened 2021-09-23 03:54 UTC by RuanGOA

Antes de fazer o PR por favor preencha o seguinte formulário:

### Meu pull request

- [x] Adiciona uma nova funcionalidade;
- [x] Conserta um bug;
- [ ] Adiciona uma documentação;
- [ ] Adiciona alguma configuração.

### O que o pull request faz?

Foi criada a página "Organizações" do projeto.
- Dentro da pasta `src/assets/icons` foi adicionado o ícone utilizado na página de Organizações.
- Dentro da pasta `src/assets/images` foi criada a pasta `organizations`, que armazena imagens mockadas das organizações. 
- Foi criado um componente container de organizações

Foi corrigido o bug de scroll horizontal, que ainda persistia. Descobri que era a propriedade `width: 100vw;` da tag `body`, no arquivo `src/styles/reset.css`. O erro era gerado quando aparecia o scroll vertical, como 100vw é um valor fixo, ele não se adaptava como um valor com `%` se adaptaria.

### Como faço para testar essa PR?

É possível testar essa PR adicionando mais valores a lista de organizações chamada de `orgs` do arquivo `src/util/organizations.js`, replicando um elemento já existente, ou adicionando outros diferentes elementos.

### Mais infos

Acredito que deixei o PR maior do que deveria novamente. Se isso for um problema, posso cancelar esse e separar os PRs da página e do componente de organizações.

### Para finalizar tenha certeza que a PR

- [ ] Está bem documentado;
- [ ] Adiciona testes se necessário;
- [ ] Passa nos testes existentes (caso existam).

### Para finalizar...

Por favor marque os revisadores @rodrigoec, @leandraoliveira, @claudiodantas e @gustavofss. Após duas aprovações a sua PR será merjada na branch `develop` até que uma release seja feita.

Bom, obrigado por sua contribuição!💙 Projetos open source só vão pra frente por causa de gente com você que está disposto(a)(e) a contribuir e manter o projeto vivo.

<div align=center>
  <img width=350px src='https://user-images.githubusercontent.com/42751604/130703676-2e16abb1-3392-4f76-a9ec-a4973f638e2d.gif'/>
</div>

2021-09-23 14:06 UTC, RodrigoEC requested changes
Muito legal @RuanGOA, parabens! Fiz somente alguns comentários pontuais 😄

2021-09-23 14:06 UTC, RodrigoEC commented on src/views/Organizacoes/index.js
> +        <OrganizationsIcon width={'2rem'} color={'#514E4E'} />
Adicionar mudança de tema na cor do ícone
```suggestion
        <OrganizationsIcon width={'2rem'} color={theme['main-font']} />
```

É só tu usar um hook useTheme nesse componente que tu consegue acessar o tema

2021-09-23 14:06 UTC, RodrigoEC commented on src/util/organizations.js
> +import opendevImage from '../assets/images/organizations/opendev.jpg'
Mover arquivo para pasta de constantes

2021-09-23 14:06 UTC, RodrigoEC commented on src/components/Organizations/style.js
> +  display: flex;
Acho que é mais interessante nesse caso utilizar o `display:grid`, digo isso pelo fato da gente querer que as orgs elas fiquem com até no máximo 3 cards em uma linha, o que não acontece em telas maiores, com o grid a gente consegue controlar melhor isso

2021-09-27 12:45 UTC, RodrigoEC requested changes
Ficou muito legal ruan! Só comentei uma coisinha relacionada ao tamanho do card.

2021-09-28 13:08 UTC, RodrigoEC requested changes
Gostei muito das alterações! Requisitei algumas mudanças em relação ao grid eo tamanho dos cards, mas de resto está tudo muito bom! 😄

2021-09-28 13:08 UTC, RodrigoEC commented on src/components/Organizations/OrganizationCard/style.js
> +  display: flex;
```suggestion
  display: flex;
  width: 25rem;
```

2021-09-28 13:08 UTC, RodrigoEC commented on src/components/Organizations/OrganizationCard/style.js
> +  width: 25rem;
```suggestion
  width: inherit;
```

2021-09-28 13:08 UTC, RodrigoEC commented on src/components/Organizations/OrganizationCard/style.js
> +  @media screen and (max-width: 1366px) {
Remover media querys aqui, já que não há necessidade de fazer o _resize_ do card.

2021-09-28 13:08 UTC, RodrigoEC commented on src/components/Organizations/style.js
> +  align-items: center;
Essa propriedade pelo que eu testei aqui não muda nenhuma propriedade visual.
```suggestion

```

2021-09-28 13:08 UTC, RodrigoEC commented on src/components/Organizations/style.js
> +  justify-content: center;
Essa propriedade pelo que eu testei aqui não muda nenhuma propriedade visual.
```suggestion

```

2021-09-28 13:08 UTC, RodrigoEC commented on src/components/Organizations/style.js
> +  flex-wrap: wrap;
Essa propriedade pelo que eu testei aqui não muda nenhuma propriedade visual.
```suggestion

```

2021-09-28 13:08 UTC, RodrigoEC commented on src/components/Organizations/style.js
> +
Para alinhar tudo e manter o gap seria interessante colocar um 
```suggestion
margin: 0 auto
```

2021-09-28 13:08 UTC, RodrigoEC commented on src/components/Organizations/style.js
> +  grid-template-columns: repeat(auto-fill, 30%);
```suggestion
  grid-template-columns: repeat(3, 1fr);
```

2021-09-28 13:08 UTC, RodrigoEC commented on src/components/Organizations/style.js
> +  @media screen and (max-width: 1366px) {
Essa mudança de template precisa acontecer em telas um pouco maiores eu acredito
```suggestion
  @media screen and (max-width: 1700px) {
```

2021-09-28 13:08 UTC, RodrigoEC commented on src/components/Organizations/style.js
> +    grid-template-columns: repeat(auto-fill, 28%);
```suggestion
    grid-template-columns: repeat(2, 1fr);
```

2021-09-28 13:08 UTC, RodrigoEC commented on src/components/Organizations/style.js
> +  @media screen and (max-width: 1024px) {
Como acontece a mudança de template da tela em telas um pouco menores acho que seria interessante deixar as duas colunas para telas um pouco menores com 925px
```suggestion
  @media screen and (max-width: 925px) {
```

2021-09-28 13:08 UTC, RodrigoEC commented on src/components/Organizations/style.js
> +    grid-template-columns: repeat(1, 75%);
```suggestion
    grid-template-columns: repeat(1, fr);
```

2021-09-29 01:31 UTC, RuanGOA commented on src/components/Organizations/style.js
> +  grid-template-columns: repeat(auto-fill, 30%);
No caso, aquele padrão do projeto no Figma de manter 2 cards quando o menu está ativo, e 3 cards quando está inativo vai ser colocado de lado, certo? Também gostei dessa forma com 3 cards em ambos xD.

2021-09-29 01:38 UTC, RuanGOA commented on src/components/Organizations/OrganizationCard/style.js
> +  display: flex;
Com essa modificações, os cards não vão ficar centralizados, era para acontecer isso mesmo? 
Como cada fr do grid é criado no geral com width maior que 25rem, a div do Card não consegue centralizar a imagem, já que ela não ocupa todo o width da coluna.

O que acha de manter o `width: 100%` na div de card, e 25rem no tamanho da tag âncora?

2021-09-29 12:53 UTC, RodrigoEC commented on src/components/Organizations/OrganizationCard/style.js
> +  display: flex;
Eu executei aqui e ta alinhado

2021-09-29 12:54 UTC, RodrigoEC commented on src/components/Organizations/OrganizationCard/style.js
> +  display: flex;
Mas não sei se tu ja commitou todas as alterações, eu executei aqui e tem algumas coisas apontadas que não foram resolvidas ainda aí talvez tu não tenha terminado.

2021-09-29 13:28 UTC, RuanGOA commented on src/components/Organizations/OrganizationCard/style.js
> +  display: flex;
EITA, não mandei ainda, esqueci desse pequeno detalhe

2021-09-29 14:05 UTC, RuanGOA commented on src/components/Organizations/OrganizationCard/style.js
> +  display: flex;
Mudanças commitadas.

2021-09-29 14:22 UTC, RodrigoEC commented on src/components/Organizations/OrganizationCard/style.js
> +  display: flex;
Pra resolver esses problemas basta tirar deixar apenas

```javaScript
export const OrganizationContainer = styled.div`
  display: flex;
  justify-content: center;
`
```

e no `OrganizationUrl` colocar a propriedade `min-width: 25rem`.

Além disso no `organizationImage` coloca a propriedade `object-fit: cover` pra ele não deixar a imagem esticada.

2021-09-29 14:33 UTC, RuanGOA commented on src/components/Organizations/OrganizationCard/style.js
> +  display: flex;
Massa, isso também resolve.

2021-09-29 15:50 UTC, RodrigoEC commented
Amigo, falta uma

2021-09-30 13:33 UTC, RodrigoEC approved these changes

2021-10-01 12:21 UTC, merged