Fix #43: Activities Page
Guardians-DSC/Front-HoCo pull request #44
Opened 2022-06-09 01:50 UTC by NicolasLopes7

### Meu pull request
#43 
- [x] Conserta um bug;

### O que o pull request faz?
- Previne a página de atividades de quebrar
- Adiciona um contexto para lidar com o modal de criar atividades
- Cria um componente para a célula de editar a atividade (previne re-render)
- Altera o estilo do overlay para ter uma melhor UI

### Como faço para testar essa PR?
Abrir o modal e ver que a tela não está crashando

2022-06-09 01:55 UTC, NicolasLopes7 commented
@rodrigoec, @leandraoliveira, @claudiodantas e @gustavofss
podem dar reviews? :)

2022-06-09 01:57 UTC, NicolasLopes7 commented on src/components/EditActivityCell/index.js
> +  record: PropTypes.any,
Se poderem esclarecer mais o tipo ficaria legal :)

2022-06-09 01:58 UTC, NicolasLopes7 commented on src/contexts/activities.context.js
> +
Também seria legal adicionar nesse componente, a criação/deleção das atividades.. E alterar o estado do modal por elas..

2022-06-09 02:01 UTC, RodrigoEC commented
Ooi @NicolasLopes7 obgg pela contribuição, amanhã faço o review :3

2022-06-10 16:57 UTC, RodrigoEC requested changes
Gostei muito das mudanças que tu colocou também, apontei só umas refatorações

2022-06-10 16:57 UTC, RodrigoEC commented on src/components/EditActivityCell/index.js
> +      {isModalActive ? <ActivityModal data={data} /> : <></>}
```suggestion
      {isModalActive && <ActivityModal data={data} />}
```

2022-06-10 16:57 UTC, RodrigoEC commented on src/views/Atividades/index.js
> +        {isModalActive ? <ActivityModal /> : <></>}
```suggestion
        {isModalActive && <ActivityModal />}
```

2022-06-10 16:57 UTC, RodrigoEC commented on src/components/EditActivityCell/index.js
> +  data: PropTypes.any,
```suggestion
  data: PropTypes.shape({
    categoria: PropTypes.string,
    creditos: PropTypes.number,
    horas: PropTypes.number,
    id: PropTypes.number,
    titulo: PropTypes.string,
    certificado: PropTypes.shape({
      titulo: PropTypes.string,
      previewURL: PropTypes.string,
    }),
  }),
```

2022-06-10 16:57 UTC, RodrigoEC commented on src/contexts/activities.context.js
> +
Verdade, seria uma boa mudar a função `handleSubmit` pra essa página, tu pode fazer isso? 😄

2022-06-10 17:02 UTC, NicolasLopes7 commented
> Verdade, seria uma boa mudar a função handleSubmit pra essa página, tu pode fazer isso? 😄
Posso sim! Se conseguir um tempinho a noite posso fazer!

2022-06-12 02:27 UTC, LeandraOS requested changes

2022-06-12 02:27 UTC, LeandraOS commented on package.json
> +}
Seria interessante adicionar uma linha vazia ao final do arquivo para o github não "reclamar"

2022-06-12 02:27 UTC, LeandraOS commented on src/contexts/activities.context.js
> +
Ótima ideia!

2022-06-12 17:23 UTC, NicolasLopes7 commented
reviews aplicados @LeandraOS @RodrigoEC !

2022-06-12 19:59 UTC, RodrigoEC commented
> reviews aplicados @LeandraOS @RodrigoEC !

Tudoo! Acho que só faltou fazer a migração do handleSubmit pra o contexto da atividade, mas o resto ta topp :3

2022-06-13 02:56 UTC, NicolasLopes7 commented on src/components/ActivityModal/index.js
> +    )
Subi a mudança @RodrigoEC, pra ser sincero achei um pouco feio kk..Pra esse PR acho que podemos deixar assim, e depois refatorar o uso de formulários, jogando eles em um objeto só, e fazendo uma função para editar-lo. Mas prefiro deixar o PR menor e não bagunçar tanto as coisas..Então acho que por enquanto tá OK esse aí

2022-06-13 03:29 UTC, NicolasLopes7 commented on src/components/ActivityModal/index.js
> +    )
pronto, criei esse [PR](https://github.com/Guardians-DSC/Front-HoCo/pull/49) implementando o hook que tinha falado.

2022-06-13 11:26 UTC, RodrigoEC commented on src/components/ActivityModal/index.js
> +    )
Certinho. hoje a noite faço a revisão final pra dar merge :3

2022-06-13 22:58 UTC, RodrigoEC approved these changes

2022-06-13 23:02 UTC, merged