creating hook to handle form changes
Guardians-DSC/Front-HoCo pull request #49
Opened 2022-06-13 03:28 UTC by NicolasLopes7

### Meu pull request

- [x] Adiciona uma nova funcionalidade;
- [ ] Conserta um bug;
- [ ] Adiciona uma documentação;
- [ ] Adiciona alguma configuração.

### O que o pull request faz?

Explica aqui qual o motivo do seu PR e quais as alterações que ele faz.

O PR adiciona um hook para lidar melhor com os formulários na aplicação, anteriormente estavamos criando um estado para cada field do nosso formulário, isso deixava nossa código muito verboso e com bastante repetição - Além de uma maior facilidade de cometer re-renders desnecessários. Para melhorar isso, criei um hook chamado `useForm`.
Ele Recebe como parâmetro inicial o estado padrão que queremos manter, após isso, expomos no formato de hook `[getters,setters]` métodos para puxarmos e manipularmos os dados do formulário.

### Como faço para testar essa PR?

Mostre nessa seção como que o(a) revisador(a) pode testar essa PR

### Mais infos

Caso você queira adicionar mais alguma informação extra, como gifs, fotos ou algum anexo, por favor adicione nessa seção

### Para finalizar tenha certeza que a PR

- [ ] Está bem documentado;
- [ ] Adiciona testes se necessário;
- [ ] Passa nos testes existentes (caso existam).

### Para finalizar...

Por favor marque os revisadores @rodrigoec, @leandraoliveira, @claudiodantas e @gustavofss. Após duas aprovações a sua PR será merjada na branch `develop` até que uma release seja feita.

Bom, obrigado por sua contribuição!💙 Projetos open source só vão pra frente por causa de gente com você que está disposto(a)(e) a contribuir e manter o projeto vivo.

<div align=center>
  <img width=350px src='https://user-images.githubusercontent.com/42751604/130703676-2e16abb1-3392-4f76-a9ec-a4973f638e2d.gif'/>
</div>

2022-06-13 03:28 UTC, NicolasLopes7 commented on src/hooks/useForm.js
> +import { useState } from 'react'
Recomendo olhar para esse arquivo primeiro, antes de começar a ler o PR.

2022-06-13 23:20 UTC, RodrigoEC requested changes

2022-06-13 23:20 UTC, RodrigoEC commented on src/hooks/useForm.js
> +import { useState } from 'react'
Eu achei muito legal a implementação do Hook de useForm, mas acho que como a gente ta usando a biblioteca AntDesign a gente poderia usar o [Form do antdesign](https://ant.design/components/form/). Esse Form permite que a gente manipule, valide e gerencie os estados de forma mais fácil

2022-06-14 00:09 UTC, NicolasLopes7 commented on src/hooks/useForm.js
> +import { useState } from 'react'
ahhh, real! perfeito então! Assim que tiver tempo mudo para utilizarmos o hook do ant

2022-06-14 13:02 UTC, RodrigoEC commented on src/hooks/useForm.js
> +import { useState } from 'react'
Ta beem😄

2022-06-15 01:27 UTC, closed without merging